export const statusOptions = [
  {
    value: "activo",
    label: 'Activo',
    color: 'success'
  },
  {
    value: "inactivo",
    label: 'Inactivo',
    color: 'info'
  }
];

export const usersList = [
  {
    "user_id": 1,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user1@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": "activo",
    "password": "+Qg8bjlUwm"
  },
  {
    "user_id": 2,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user2@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": "activo",
    "password": "Ho9S&RL5N;"
  },
  {
    "user_id": 3,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user3@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": "activo",
    "password": "@VGMuKKb;a"
  },
  {
    "user_id": 4,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user4@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": "activo",
    "password": "9P5v8J&*{M"
  },
  {
    "user_id": 5,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user5@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": "activo",
    "password": "fR8(YDB>FO"
  },
  {
    "user_id": 6,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user6@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": "activo",
    "password": "y5{.?joH05"
  },
  {
    "user_id": 7,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user7@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": "activo",
    "password": "PBn%aHzVQ3"
  },
  {
    "user_id": 8,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user8@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": "activo",
    "password": "w2EOeEJqsH"
  },
  {
    "user_id": 9,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user9@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": "activo",
    "password": "A$2kZ(AX0S"
  },
  {
    "user_id": 10,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user10@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": "activo",
    "password": "ECs{E&5UUL"
  },
  {
    "user_id": 11,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user11@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": "activo",
    "password": "I9M#>j{k_#"
  },
  {
    "user_id": 12,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user12@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": "activo",
    "password": ">AkpTzB3[X"
  },
  {
    "user_id": 13,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user13@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": "inactivo",
    "password": "%BL0-(|}8w"
  },
  {
    "user_id": 14,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user14@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": "inactivo",
    "password": "*)F:9qX.Kc"
  },
  {
    "user_id": 15,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user15@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": "inactivo",
    "password": "V^Uzqa^WAG"
  },
  {
    "user_id": 16,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user16@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": "inactivo",
    "password": "xNh]dbz5YY"
  },
  {
    "user_id": 17,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user17@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": "inactivo",
    "password": "EiNzn<=ywI"
  },
  {
    "user_id": 18,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user18@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": "inactivo",
    "password": "FGt2:d3i=g"
  },
  {
    "user_id": 19,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user19@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "=Nj*34]7Mj"
  },
  {
    "user_id": 20,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user20@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "R1LtBnig43"
  },
  {
    "user_id": 21,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user21@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "noPAVPAC#X"
  },
  {
    "user_id": 22,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user22@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "F81)4QNkci"
  },
  {
    "user_id": 23,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user23@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "+giiA3{pi5"
  },
  {
    "user_id": 24,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user24@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "HP2]%O#A_{"
  },
  {
    "user_id": 25,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user25@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "Xu@He0eV$q"
  },
  {
    "user_id": 26,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user26@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "kV7I>inr?-"
  },
  {
    "user_id": 27,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user27@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "GwCn+kU6=0"
  },
  {
    "user_id": 28,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user28@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "YT|B#y2fm%"
  },
  {
    "user_id": 29,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user29@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "sB[GoPf]@["
  },
  {
    "user_id": 30,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user30@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "GYX66XuPjy"
  },
  {
    "user_id": 31,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user31@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "Co07,Pp4k_"
  },
  {
    "user_id": 32,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user32@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "zID2fk&N4J"
  },
  {
    "user_id": 33,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user33@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "&[ibO}F@Uq"
  },
  {
    "user_id": 34,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user34@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "ZB+2=4XhA6"
  },
  {
    "user_id": 35,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user35@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": ".RqWExZu1]"
  },
  {
    "user_id": 36,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user36@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "NLNKqEE([8"
  },
  {
    "user_id": 37,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user37@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "%|;-HVx4ff"
  },
  {
    "user_id": 38,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user38@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "!rm-J.$heo"
  },
  {
    "user_id": 39,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user39@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "?AS7-{|nEX"
  },
  {
    "user_id": 40,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user40@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "-sgrRG6xB%"
  },
  {
    "user_id": 41,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user41@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "Jnd@T7d4LN"
  },
  {
    "user_id": 42,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user42@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "S_BSXohd=8"
  },
  {
    "user_id": 43,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user43@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "isvwsp&x*H"
  },
  {
    "user_id": 44,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user44@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "FCQx9c5JHM"
  },
  {
    "user_id": 45,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user45@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "1EKN1ltIBH"
  },
  {
    "user_id": 46,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user46@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "s9m#GfDOlq"
  },
  {
    "user_id": 47,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user47@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": ")egi:yWI2j"
  },
  {
    "user_id": 48,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user48@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "UuMkPPBasW"
  },
  {
    "user_id": 49,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user49@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "-#IlSt;I{i"
  },
  {
    "user_id": 50,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user50@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "]|.Vb6SrbY"
  },
  {
    "user_id": 51,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user51@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "b<UZ(=24C9"
  },
  {
    "user_id": 52,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user52@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "65y}v+fVT@"
  },
  {
    "user_id": 53,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user53@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "<*s3h>Q-c]"
  },
  {
    "user_id": 54,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user54@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "fB2ya$|IZ1"
  },
  {
    "user_id": 55,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user55@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "<@Pytifbu."
  },
  {
    "user_id": 56,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user56@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "1av2#|Guc9"
  },
  {
    "user_id": 57,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user57@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "rb|[GQ}o=9"
  },
  {
    "user_id": 58,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user58@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "T},8juqmEp"
  },
  {
    "user_id": 59,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user59@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "%WqC?Zz+v;"
  },
  {
    "user_id": 60,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user60@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "qfU,oll{|{"
  },
  {
    "user_id": 61,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user61@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "7fj%^D5b.3"
  },
  {
    "user_id": 62,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user62@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "y82P{t7+kh"
  },
  {
    "user_id": 63,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user63@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "vc|R&Z,9D#"
  },
  {
    "user_id": 64,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user64@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "r4cYkWH{4|"
  },
  {
    "user_id": 65,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user65@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "j=6A%pftIb"
  },
  {
    "user_id": 66,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user66@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "(v@,N=scM^"
  },
  {
    "user_id": 67,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user67@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "y1I1q+t%4&"
  },
  {
    "user_id": 68,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user68@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "Fdr[e|W6}g"
  },
  {
    "user_id": 69,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user69@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "(k2iFaQ_h&"
  },
  {
    "user_id": 70,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user70@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "k{B&$UMQ[V"
  },
  {
    "user_id": 71,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user71@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": ":BIj0ByCUB"
  },
  {
    "user_id": 72,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user72@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "rfMc8opM:m"
  },
  {
    "user_id": 73,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user73@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "7t+,7q-(>1"
  },
  {
    "user_id": 74,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user74@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "DmMtGP1q+p"
  },
  {
    "user_id": 75,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user75@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "Na9{FI+<}v"
  },
  {
    "user_id": 76,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user76@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "9w6[4*ud#M"
  },
  {
    "user_id": 77,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user77@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "ba9J]nuSDb"
  },
  {
    "user_id": 78,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user78@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "N,RJ146ClT"
  },
  {
    "user_id": 79,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user79@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "r{hNmQ6USj"
  },
  {
    "user_id": 80,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user80@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "^rEP!vT5(1"
  },
  {
    "user_id": 81,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user81@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "N1E56Z+ij9"
  },
  {
    "user_id": 82,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user82@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "1pD$c7u<7o"
  },
  {
    "user_id": 83,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user83@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "]Bai4g}B*2"
  },
  {
    "user_id": 84,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user84@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "5<ygZK-_;S"
  },
  {
    "user_id": 85,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user85@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "%B?)cudn!@"
  },
  {
    "user_id": 86,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user86@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "2mX2S!rG!!"
  },
  {
    "user_id": 87,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user87@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "!M,$;Cb@Tw"
  },
  {
    "user_id": 88,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user88@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": ";d^Z*qe2iz"
  },
  {
    "user_id": 89,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user89@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": ">z!,W4>7ji"
  },
  {
    "user_id": 90,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user90@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "dR8!KjQ7}n"
  },
  {
    "user_id": 91,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user91@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "}}qam|5,7W"
  },
  {
    "user_id": 92,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user92@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "A|Yab!}BcG"
  },
  {
    "user_id": 93,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user93@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "1dp7EY86gA"
  },
  {
    "user_id": 94,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user94@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "?[[[CR6ooc"
  },
  {
    "user_id": 95,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user95@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "tBhgp?ZAVP"
  },
  {
    "user_id": 96,
    "name": "Chiquita Flament",
    "avatar": "/images/200x200.png",
    "age": 39,
    "email": "user96@example.com",
    "phone": "312-329-5963",
    "role": "author",
    "status": false,
    "password": "t_vILgq<zW"
  },
  {
    "user_id": 97,
    "name": "Ludvig Kennea",
    "avatar": "/images/200x200.png",
    "age": 55,
    "email": "user97@example.com",
    "phone": "398-181-0799",
    "role": "admin",
    "status": false,
    "password": "jJvbUeziWT"
  },
  {
    "user_id": 98,
    "name": "Kelvin Keuning",
    "avatar": "/images/200x200.png",
    "age": 57,
    "email": "user98@example.com",
    "phone": "177-302-1065",
    "role": "admin",
    "status": true,
    "password": "(oC7f3(v^F"
  },
  {
    "user_id": 99,
    "name": "Homere O'Noulane",
    "avatar": "/images/200x200.png",
    "age": 23,
    "email": "user99@example.com",
    "phone": "673-942-1852",
    "role": "author",
    "status": true,
    "password": "|xbn#qv#H*"
  },
  {
    "user_id": 100,
    "name": "Kriste Salerno",
    "avatar": null,
    "age": 29,
    "email": "user100@example.com",
    "phone": "355-451-1490",
    "role": "author",
    "status": true,
    "password": "W{[jk5Kg5f"
  }
]
